name: stepwise
description: A new Flutter project.

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none'

# Version info
version: 1.0.0+1

# Environment settings
environment:
  sdk: ^3.6.1

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.1
  pedometer: ^4.0.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    # - lib/assets/your_model.tflite  # Uncomment if you have these
    # - lib/assets/your_labels.txt    # Uncomment if you have these

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
