name: stepwise
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.1
  pedometer: ^4.0.1
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    # Uncomment the following if you have these assets:
    # - lib/assets/your_model.tflite
    # - lib/assets/your_labels.txt

  fonts:
    - family: GoogleSans
      fonts:
        - asset: lib/assets/fonts/GoogleSans-Regular.ttf
